"""Load pre-generated synthetic deal notes from disk."""
import json
from dataclasses import dataclass
from pathlib import Path


@dataclass
class RawDocument:
    text: str
    source_id: str
    doc_type: str
    metadata: dict


def load_synthetic(data_dir: str | Path = "data/raw/synthetic") -> list[RawDocument]:
    """
    Load synthetic deal notes generated by scripts/generate_synthetic.py.

    Expected file format: one JSON per file, or a JSONL file.
    Each record: {"id": str, "text": str, "industry": str, "icp": str}
    """
    data_path = Path(data_dir)
    docs: list[RawDocument] = []

    # Support both individual .json files and .jsonl batches
    for path in sorted(data_path.glob("**/*.json*")):
        if path.suffix == ".jsonl":
            with open(path) as f:
                for line in f:
                    record = json.loads(line)
                    doc = _record_to_doc(record)
                    if doc is not None:
                        docs.append(doc)
        else:
            with open(path) as f:
                record = json.load(f)
                if isinstance(record, list):
                    docs.extend(d for r in record if (d := _record_to_doc(r)) is not None)
                else:
                    doc = _record_to_doc(record)
                    if doc is not None:
                        docs.append(doc)

    return docs


def _record_to_doc(record: dict) -> RawDocument | None:
    text = record.get("text")
    if not text:
        return None
    return RawDocument(
        text=text,
        source_id=record.get("id", record.get("source_id", "unknown")),
        doc_type="deal_note",
        metadata={
            "industry": record.get("industry", ""),
            "icp": record.get("icp", ""),
        },
    )
